#!/bin/bash
# pip install gnuplot_kernel
python -m pip install -e 'git+git://github.com/ouseful-PR/gnuplot_kernel.git#egg=gnuplot-kernel'
#pip install -e git://github.com/ouseful-PR/gnuplot_kernel.git#egg=gnuplot-kernel
python -m gnuplot_kernel install --user
